<a href="https://colab.research.google.com/github/anas1IA/Analysis-of-Bank-Debit-Collections/blob/main/Implimentation_logistic_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [45]:
df=pd.read_csv("binary.csv")
data = df.to_numpy()

In [51]:
df.describe()

admit         gre         gpa       rank
count  400.000000  400.000000  400.000000  400.00000
mean     0.317500  587.700000    3.389900    2.48500
std      0.466087  115.516536    0.380567    0.94446
min      0.000000  220.000000    2.260000    1.00000
25%      0.000000  520.000000    3.130000    2.00000
50%      0.000000  580.000000    3.395000    2.00000
75%      1.000000  660.000000    3.670000    3.00000
max      1.000000  800.000000    4.000000    4.00000

In [127]:
def prepare_data(X, y):
    x_ = ((X - X.mean(axis=0))/X.std(axis=0))
    x_ = np.hstack((np.ones((len(x_), 1)), x_))
    y_ = np.where(y==0, -1, 1)
    return x_, y_

In [204]:
X_train, y_train = prepare_data(data[:, 1:], data[:, 0])

In [ ]:
data[:,1:]

In [205]:
X_train

array([[ 1.        , -1.80026271,  0.57907221,  0.54596793],
       [ 1.        ,  0.62666824,  0.73692924,  0.54596793],
       [ 1.        ,  1.84013372,  1.60514292, -1.57429586],
       ...,
       [ 1.        , -1.10685387, -1.99925931, -0.51416397],
       [ 1.        ,  0.97337266,  0.68431023, -0.51416397],
       [ 1.        ,  0.10661161,  1.31573836,  0.54596793]])

In [129]:
#implimenation Phi function
def Phi(x):
  return 1/(1+np.exp(-x))

In [130]:
def hs(w,x):
  return w@x

In [131]:
def ls(x,y,w):
  return -np.log(Phi(y*hs(w,x)))

In [132]:
def  loss_function_Emr(X,y,w):
  n=X.shape[0]
  erreur=[ls(X[i],y[i],w) for i in range(n)]
  return  np.sum(erreur)/n

In [207]:
loss_function_Emr(X_train,y_train, np.array([0,0,0,0]))

0.6931471805599452

In [176]:
def gradient_descent(X,Y,w):
  n=X.shape[0]
  gar=np.array([-Phi(-Y[i]*hs(w,X[i]))*(Y[i]*X[i]) for i in range(n)])
  return gar.sum(axis=0)/n

In [208]:
gradient_descent(X_train,y_train, np.array([0,0,0,0]))

array([ 0.1825    , -0.08585485, -0.08295847,  0.1128908 ])

In [209]:
def Logistic_regression(X,y,w0,lr=0.01, Tmax=3000, eps=1e-2):

  w = np.copy(w0)
  t = 0
  gd = gradient_descent(X,y,w)
  while Tmax > t and np.linalg.norm(gd) > eps:
    gd = gradient_descent(X,y,w)
    w -= lr *gd
    t += 1

  return w

In [211]:
wl = Logistic_regression(X_train, y_train, np.random.random((4,)), Tmax=4000, eps=2e-2)

In [212]:
wl

array([-0.78686295,  0.30189915,  0.26201259, -0.43021983])

In [213]:
y_pred = np.where(Phi(hs(X_train, wl)) > 0.5, 1,-1)

In [214]:
np.array(list(map(lambda x,y : 0 if x==y else 1, y_pred, y_train))).sum()/400


0.295

In [215]:
loss_function_Emr(X_train,y_train, wl)

0.5755782921644433